using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace PermissionManifest.Generator;

/// <summary>
/// Discovers call sites that invoke <c>[RequiresPermission]</c>-annotated methods and
/// aggregates their permissions into a distinct, deterministically ordered manifest.
///
/// The aggregated manifest is surfaced as a generated <c>const string</c> holding the
/// manifest JSON. This generator never touches the filesystem; writing the artifact to
/// disk is owned by the build-emission layer.
/// </summary>
[Generator]
public sealed class PermissionManifestGenerator : IIncrementalGenerator
{
    private const string AttributeShortName = "RequiresPermission";
    private const string AttributeFullName = "RequiresPermissionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Every invocation expression is a candidate call site. Runtime reachability is
        // deliberately ignored: statically visible call sites are aggregated regardless of
        // surrounding guards, so runtime-variant permissions stay conservatively included.
        IncrementalValuesProvider<string?> permissions = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is InvocationExpressionSyntax,
                static (syntaxContext, _) => ResolvePermission(syntaxContext))
            .Where(static permission => permission is not null);

        context.RegisterSourceOutput(permissions.Collect(), static (productionContext, permissions) =>
        {
            string[] manifest = permissions
                .Select(static permission => permission!)
                .Distinct(StringComparer.Ordinal)
                .OrderBy(static permission => permission, StringComparer.Ordinal)
                .ToArray();

            string json = BuildManifestJson(manifest);
            productionContext.AddSource(
                "PermissionManifest.g.cs",
                SourceText.From(BuildGeneratedSource(json), Encoding.UTF8));
        });
    }

    /// <summary>
    /// Resolves the invoked method symbol and returns the <c>RequiresPermission</c>
    /// permission argument, or <c>null</c> when the call site carries no permission.
    /// </summary>
    private static string? ResolvePermission(GeneratorSyntaxContext context)
    {
        if (context.SemanticModel.GetSymbolInfo((InvocationExpressionSyntax)context.Node).Symbol
            is not IMethodSymbol method)
        {
            return null;
        }

        foreach (AttributeData attribute in method.GetAttributes())
        {
            string? name = attribute.AttributeClass?.Name;
            if (name is not (AttributeShortName or AttributeFullName))
            {
                continue;
            }

            if (attribute.ConstructorArguments.Length == 1
                && attribute.ConstructorArguments[0] is { Kind: TypedConstantKind.Primitive, Value: string permission }
                && !string.IsNullOrWhiteSpace(permission))
            {
                return permission;
            }
        }

        return null;
    }

    private static string BuildManifestJson(IReadOnlyList<string> permissions)
    {
        var json = new StringBuilder();
        json.Append("{\"permissions\":[");
        for (var i = 0; i < permissions.Count; i++)
        {
            if (i > 0)
            {
                json.Append(',');
            }

            AppendJsonString(json, permissions[i]);
        }

        json.Append("]}");
        return json.ToString();
    }

    private static void AppendJsonString(StringBuilder builder, string value)
    {
        builder.Append('"');
        foreach (char c in value)
        {
            switch (c)
            {
                case '"': builder.Append("\\\""); break;
                case '\\': builder.Append("\\\\"); break;
                case '\b': builder.Append("\\b"); break;
                case '\f': builder.Append("\\f"); break;
                case '\n': builder.Append("\\n"); break;
                case '\r': builder.Append("\\r"); break;
                case '\t': builder.Append("\\t"); break;
                default:
                    if (c < ' ')
                    {
                        builder.Append("\\u").Append(((int)c).ToString("x4"));
                    }
                    else
                    {
                        builder.Append(c);
                    }

                    break;
            }
        }

        builder.Append('"');
    }

    private static string BuildGeneratedSource(string json)
    {
        return $@"// <auto-generated />
namespace PermissionManifest.Generated;

/// <summary>
/// Permission manifest aggregated from statically visible RequiresPermission call sites.
/// </summary>
internal static class PermissionManifest
{{
    public const string Json = {SymbolDisplay.FormatLiteral(json, quote: true)};
}}
";
    }
}
